# Docker ?? ??? (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/realworld
spring.datasource.username=your_user
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update
