# Docker ?? ??? (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/realworld
spring.datasource.username=devuser
spring.datasource.password=devpass
spring.jpa.hibernate.ddl-auto=update
